# 请保存为UTF-8格式
spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev  #开发环境
  application:
    name: springcloud-config-jxd-dev
---
spring:
  profiles: test
  application:
    name: springcloud-config-jxd-test
